# Generated by Django 4.0.8 on 2024-01-23 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_cmdb', '0035_vlan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afisafi',
            name='route_policy_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_in', to='netbox_cmdb.routepolicy'),
        ),
        migrations.AlterField(
            model_name='afisafi',
            name='route_policy_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_out', to='netbox_cmdb.routepolicy'),
        ),
        migrations.AlterField(
            model_name='bgppeergroup',
            name='route_policy_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_in', to='netbox_cmdb.routepolicy'),
        ),
        migrations.AlterField(
            model_name='bgppeergroup',
            name='route_policy_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_out', to='netbox_cmdb.routepolicy'),
        ),
        migrations.AlterField(
            model_name='devicebgpsession',
            name='peer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='netbox_cmdb.bgppeergroup'),
        ),
        migrations.AlterField(
            model_name='devicebgpsession',
            name='route_policy_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_in', to='netbox_cmdb.routepolicy'),
        ),
        migrations.AlterField(
            model_name='devicebgpsession',
            name='route_policy_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_out', to='netbox_cmdb.routepolicy'),
        ),
        migrations.AlterField(
            model_name='routepolicyterm',
            name='from_bgp_community_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='netbox_cmdb.bgpcommunitylist'),
        ),
        migrations.AlterField(
            model_name='routepolicyterm',
            name='from_prefix_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='netbox_cmdb.prefixlist'),
        ),
    ]
